const D=window.DASH_DATA; const view=document.querySelector('#view');
const fmtInt=n=>n==null?'—':new Intl.NumberFormat('pt-BR').format(n);
const fmtMoney=n=>n===0?'Não informado/sem valor positivo':new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(n);
function kpis(){
  const r=D.regional; const federais=r.filter(x=>x.cargo.includes('Federal')).length; const estaduais=r.filter(x=>x.cargo.includes('Estadual')).length;
  document.querySelector('#kpis').innerHTML=`<div class="kpi"><div class="label">Candidatos regionais</div><div class="value">${r.length}</div><div class="hint">Noroeste, Alto Paranaíba e entorno</div></div><div class="kpi"><div class="label">Federais monitorados</div><div class="value">${federais}</div><div class="hint">Modelo Monte Carlo</div></div><div class="kpi"><div class="label">Estaduais monitorados</div><div class="value">${estaduais}</div><div class="hint">Modelo Monte Carlo</div></div><div class="kpi"><div class="label">Cargos majoritários</div><div class="value">3</div><div class="hint">Presidente, governador e 2 vagas no Senado</div></div>`;
}
function regional(){
 view.innerHTML=`<div class="section-title"><div><h2>Candidaturas regionais</h2><p>Probabilidade estimada pelo Monte Carlo v2 já discutido; não é pesquisa eleitoral.</p></div></div><div class="toolbar"><input id="q" placeholder="Buscar candidato ou cidade…"><select id="cargo"><option value="">Todos os cargos</option><option>Deputado Federal</option><option>Deputado Estadual</option></select><select id="ord"><option value="prob">Ordenar por probabilidade</option><option value="votos">Ordenar por votação anterior</option><option value="patrimonio">Ordenar por patrimônio</option></select></div><div id="cards" class="grid"></div>`;
 const draw=()=>{let a=[...D.regional]; const q=document.querySelector('#q').value.toLowerCase(); const c=document.querySelector('#cargo').value; const o=document.querySelector('#ord').value; a=a.filter(x=>(!q||`${x.nome} ${x.base} ${x.partido}`.toLowerCase().includes(q))&&(!c||x.cargo===c)); a.sort((x,y)=>o==='votos'?(y.ultimaVotacao||0)-(x.ultimaVotacao||0):o==='patrimonio'?y.patrimonio-x.patrimonio:y.prob-x.prob); document.querySelector('#cards').innerHTML=a.map(x=>`<article class="card"><div class="card-head"><div><div class="name">${x.nome}</div><div class="meta">${x.cargo} • ${x.partido}</div><span class="badge">${x.base}</span></div><div class="number">${x.numero}</div></div><div class="metric-row"><div class="metric"><span>Última votação</span><strong>${fmtInt(x.ultimaVotacao)}</strong><small>${x.ultimaEleicao}</small></div><div class="metric"><span>Patrimônio 2026</span><strong>${fmtMoney(x.patrimonio)}</strong></div></div><div class="prob"><div class="prob-head"><span>Probabilidade do modelo</span><strong>${x.prob.toFixed(1)}%</strong></div><div class="bar"><i style="width:${x.prob}%"></i></div></div>${x.nota?`<p class="status">${x.nota}</p>`:''}</article>`).join('')}; ['q','cargo','ord'].forEach(id=>document.querySelector('#'+id).addEventListener('input',draw)); draw();
}
function majoritario(key,title,description,pollLabel){ const arr=D[key]; const poll=arr.filter(x=>x.poll!=null).sort((a,b)=>b.poll-a.poll); view.innerHTML=`<div class="section-title"><div><h2>${title}</h2><p>${description}</p></div></div>${poll.length?`<div class="card"><div class="name">Último recorte de pesquisa utilizado no painel</div><div class="meta">${pollLabel}</div><div class="poll">${poll.map(x=>`<div class="poll-line"><div class="poll-name">${x.nome}</div><div class="poll-track"><div class="poll-fill" style="width:${Math.max(1,x.poll)}%"></div></div><div class="poll-value">${x.poll}%</div></div>`).join('')}</div></div>`:''}<div class="table-wrap" style="margin-top:14px"><table><thead><tr><th>Candidato</th><th>Número</th><th>Partido</th><th>Pesquisa no painel</th><th>Observação</th></tr></thead><tbody>${arr.map(x=>`<tr><td><strong>${x.nome}</strong></td><td>${x.numero}</td><td>${x.partido}</td><td>${x.poll==null?'—':x.poll+'%'}</td><td class="status">${x.status||'Pedido de registro sujeito ao julgamento eleitoral'}</td></tr>`).join('')}</tbody></table></div><div class="note">Para evitar falsa precisão, o painel só mostra percentuais quando o candidato consta no recorte da pesquisa utilizada. Ausência de percentual não significa 0%.</div>`; }
function metodo(){view.innerHTML=`<div class="section-title"><div><h2>Metodologia e transparência</h2><p>Como ler os números do painel.</p></div></div><div class="method"><div class="card"><h3>Monte Carlo dos deputados regionais</h3><ul><li>As probabilidades são cenários simulados, não pesquisas.</li><li>Entram como premissas: votação anterior, força territorial, incumbência, incerteza de expansão regional e efeito da legenda no sistema proporcional.</li><li>O sistema proporcional impede definir um corte individual fixo: a votação total do partido/federação e as sobras alteram a linha de eleição.</li><li>O painel deve ser recalibrado sempre que surgirem novas pesquisas, composição definitiva das chapas ou dados oficiais relevantes.</li></ul></div><div class="card"><h3>Fontes principais</h3><ul><li><a href="${D.fontes.tse}" target="_blank">Dados Abertos do TSE — Candidatos 2026</a></li><li><a href="${D.fontes.gov}" target="_blank">Lista Governo de MG baseada no TSE</a></li><li><a href="${D.fontes.sen}" target="_blank">Lista Senado por MG baseada no TSE</a></li><li><a href="${D.fontes.pres}" target="_blank">Lista e números presidenciais baseada no TSE</a></li></ul></div></div><div class="note"><strong>Importante:</strong> patrimônio declarado não equivale necessariamente ao patrimônio líquido ou valor de mercado atual. Pesquisas têm metodologia, amostra e margem de erro próprias. A candidatura pode mudar de situação durante o julgamento pela Justiça Eleitoral.</div>`}
function show(v){document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.view===v)); if(v==='regional')regional(); else if(v==='governador')majoritario('governador','Governo de Minas Gerais','Lista registrada para 2026 e último recorte estadual incorporado.','Datafolha, 21 ago 2026 — 1.204 eleitores, margem de erro ±3 p.p.'); else if(v==='senado')majoritario('senado','Senado Federal — Minas Gerais','Em 2026, cada eleitor mineiro votará em dois candidatos ao Senado.','Datafolha, 21 ago 2026 — 1.204 eleitores, margem de erro ±3 p.p.'); else if(v==='presidente')majoritario('presidente','Presidência da República','Treze pedidos de registro compõem a disputa presidencial no painel.','BTG/Nexus, 24 ago 2026 — 2.006 eleitores, margem de erro ±2 p.p.'); else metodo();}
document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>show(b.dataset.view))); kpis(); show('regional');
