window.DASH_DATA = {
  regional: [
    {nome:'Greyce Elias',cargo:'Deputada Federal',partido:'PL',numero:'2270',base:'Patrocínio / Alto Paranaíba',patrimonio:2110000,ultimaVotacao:110346,ultimaEleicao:'Federal 2022',prob:92.2},
    {nome:'Lud Falcão',cargo:'Deputada Estadual',partido:'Republicanos',numero:'10000',base:'Patos de Minas / Alto Paranaíba',patrimonio:10479.34,ultimaVotacao:59381,ultimaEleicao:'Estadual 2022',prob:87.3},
    {nome:'Bosco',cargo:'Deputado Estadual',partido:'PSD',numero:'55200',base:'Araxá / Alto Paranaíba',patrimonio:2385183.83,ultimaVotacao:70807,ultimaEleicao:'Estadual 2022',prob:87.1},
    {nome:'Igor Santos',cargo:'Deputado Federal',partido:'PL',numero:'2227',base:'Paracatu / Noroeste',patrimonio:904139.22,ultimaVotacao:40976,ultimaEleicao:'Prefeito 2024',prob:71.4},
    {nome:'José Eustáquio',cargo:'Deputado Federal',partido:'MDB',numero:'1590',base:'Patos de Minas / Alto Paranaíba',patrimonio:1156600,ultimaVotacao:1948,ultimaEleicao:'Vereador 2024',prob:50.4,nota:'Também recebeu 18.220 votos para deputado federal em 2022.'},
    {nome:'Marli Ribeiro',cargo:'Deputada Estadual',partido:'PL',numero:'22022',base:'Patos de Minas / Paracatu',patrimonio:201359.18,ultimaVotacao:31340,ultimaEleicao:'Estadual 2022',prob:45.4},
    {nome:'Dr. Julio Mundim',cargo:'Deputado Federal',partido:'PSDB',numero:'4522',base:'Paracatu / Noroeste',patrimonio:20042500,ultimaVotacao:null,ultimaEleicao:'Estreante',prob:44.7},
    {nome:'Gladston Gabriel',cargo:'Deputado Federal',partido:'PL',numero:'2202',base:'Patos de Minas / Alto Paranaíba',patrimonio:1216000,ultimaVotacao:1300,ultimaEleicao:'Vereador 2024',prob:43.9},
    {nome:'Maria Clara Marra',cargo:'Deputada Estadual',partido:'PSDB',numero:'45300',base:'Patrocínio / Alto Paranaíba',patrimonio:634796.49,ultimaVotacao:42415,ultimaEleicao:'Estadual 2022',prob:43.7},
    {nome:'Fernando Breno',cargo:'Deputado Estadual',partido:'PRD',numero:'25123',base:'Coromandel / Alto Paranaíba',patrimonio:606491.40,ultimaVotacao:14009,ultimaEleicao:'Prefeito 2024',prob:39.9},
    {nome:'Cabo Santana',cargo:'Deputado Federal',partido:'Republicanos',numero:'1024',base:'Unaí / Noroeste',patrimonio:146469.60,ultimaVotacao:null,ultimaEleicao:'Estreante',prob:14.6},
    {nome:'Ju Almeida',cargo:'Deputada Federal',partido:'Republicanos',numero:'1029',base:'Carmo do Paranaíba / Paracatu',patrimonio:288000,ultimaVotacao:429,ultimaEleicao:'Vereadora 2024',prob:9.7},
    {nome:'Clesle Siqueira',cargo:'Deputado Federal',partido:'União Brasil',numero:'4407',base:'Paracatu / Noroeste',patrimonio:103191,ultimaVotacao:412,ultimaEleicao:'Vereador 2024',prob:5.3},
    {nome:'Silva Brasil',cargo:'Deputado Federal',partido:'União Brasil',numero:'4490',base:'Patos de Minas / Alto Paranaíba',patrimonio:0,ultimaVotacao:null,ultimaEleicao:'Estreante',prob:6.4},
    {nome:'João Paulo Nagashi',cargo:'Deputado Federal',partido:'Missão',numero:'1445',base:'Patos de Minas / Alto Paranaíba',patrimonio:0,ultimaVotacao:null,ultimaEleicao:'Estreante',prob:0.9},
    {nome:'Elismar Prado',cargo:'Deputado Estadual',partido:'PSD',numero:'55100',base:'Uberlândia / Triângulo',patrimonio:1703029.96,ultimaVotacao:83344,ultimaEleicao:'Estadual 2022',prob:94.1},
    {nome:'Raul Belém',cargo:'Deputado Estadual',partido:'PSD',numero:'55700',base:'Araguari / Triângulo',patrimonio:1663000,ultimaVotacao:76329,ultimaEleicao:'Estadual 2022',prob:88.2}
  ],
  governador: [
    {nome:'Cleitinho Azevedo',numero:'10',partido:'Republicanos',poll:32},
    {nome:'Patrus Ananias',numero:'13',partido:'PT',poll:12},
    {nome:'Alexandre Kalil',numero:'12',partido:'PDT',poll:12},
    {nome:'Mateus Simões',numero:'55',partido:'PSD',poll:4},
    {nome:'Flávio Roscoe',numero:'22',partido:'PL',poll:4},
    {nome:'Gabriel Azevedo',numero:'15',partido:'MDB',poll:4},
    {nome:'Rafael Ribeiro de Ávila',numero:'16',partido:'PSTU',poll:null},
    {nome:'Benoni Benjamin Cardoso Mendes',numero:'14',partido:'Missão',poll:null},
    {nome:'Tulio Cesar Dias Lopes',numero:'21',partido:'PCB',poll:null},
    {nome:'Henrique Areas de Araujo',numero:'29',partido:'PCO',poll:null},
    {nome:'Indira Ivanise Xavier',numero:'80',partido:'UP',poll:null}
  ],
  senado: [
    {nome:'Marília Campos',numero:'131',partido:'PT',poll:11},
    {nome:'Carlos Viana',numero:'555',partido:'PSD',poll:8},
    {nome:'Domingos Sávio',numero:'222',partido:'PL',poll:6},
    {nome:'Marcelo Aro',numero:'111',partido:'PP',poll:5},
    {nome:'Ana Luiza do MLB',numero:'808',partido:'UP',poll:4},
    {nome:'Marco Antônio Superman',numero:'300',partido:'Novo',poll:3},
    {nome:'Áurea Carolina',numero:'500',partido:'PSOL',poll:null},
    {nome:'Ramon Moreira',numero:'277',partido:'DC',poll:null},
    {nome:'Gustavo Galassi',numero:'456',partido:'PSDB',poll:null},
    {nome:'Fidelis Oliveira Alcantara',numero:'800',partido:'UP',poll:null},
    {nome:'Arcanjo Carlos Pimenta',numero:'155',partido:'MDB',poll:null},
    {nome:'Sebastião de Oliveira Pessoa',numero:'290',partido:'PCO',poll:null},
    {nome:'Marcelo Heringer',numero:'123',partido:'PDT',poll:null},
    {nome:'Jordano Carvalho dos Santos',numero:'160',partido:'PSTU',poll:null},
    {nome:'Victoria de Fátima de Mello',numero:'161',partido:'PSTU',poll:null},
    {nome:'Carlos Magno de Moura Soares',numero:'700',partido:'Avante',poll:null},
    {nome:'Manoel Teodoro Pereira de Carvalho Filho',numero:'150',partido:'MDB',poll:null}
  ],
  presidente: [
    {nome:'Lula',numero:'13',partido:'PT',poll:41},
    {nome:'Flávio Bolsonaro',numero:'22',partido:'PL',poll:37},
    {nome:'Ronaldo Caiado',numero:'55',partido:'PSD',poll:5},
    {nome:'Renan Santos',numero:'14',partido:'Missão',poll:3},
    {nome:'Romeu Zema',numero:'30',partido:'Novo',poll:3},
    {nome:'Augusto Cury',numero:'70',partido:'Avante',poll:2},
    {nome:'Samara Martins',numero:'80',partido:'UP',poll:1},
    {nome:'Clariana Barão',numero:'27',partido:'DC',poll:0},
    {nome:'Pablo Marçal',numero:'28',partido:'PRTB',poll:null,status:'Registro sob análise; inelegibilidade é objeto de disputa judicial.'},
    {nome:'Rui Costa Pimenta',numero:'29',partido:'PCO',poll:0},
    {nome:'Edmilson Costa',numero:'21',partido:'PCB',poll:0},
    {nome:'Hertz Dias',numero:'16',partido:'PSTU',poll:0},
    {nome:'Veterinário Wilson Grassi',numero:'35',partido:'Democrata',poll:0}
  ],
  fontes: {
    tse:'https://dadosabertos.tse.jus.br/dataset/candidatos-2026',
    gov:'https://noticias.uol.com.br/eleicoes/2026/08/24/veja-lista-dos-candidatos-a-governador-de-minas-gerais-em-2026.ghtm',
    sen:'https://noticias.uol.com.br/eleicoes/2026/08/24/veja-lista-dos-candidatos-ao-senado-por-minas-gerais-em-2026.ghtm',
    pres:'https://noticias.uol.com.br/eleicoes/2026/08/18/lula-13-flavio-22-veja-numeros-dos-candidatos-a-presidente-em-2026.ghtm'
  }
};
