(() => {
  const view=document.querySelector('#view');
  const safe=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0});
  const fmtDate=iso=>{if(!iso)return '—';const d=new Date(iso);return Number.isNaN(d.getTime())?iso:new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short',timeZone:'America/Sao_Paulo'}).format(d)};
  const statusClass=s=>{const x=String(s||'').toUpperCase();if(x.includes('DEFERID')||x.includes('APTO'))return'tse-ok';if(x.includes('INDEFER')||x.includes('CANCEL')||x.includes('RENUNC'))return'tse-bad';return'tse-warn'};
  const fetchJson=async p=>{const r=await fetch(p,{cache:'no-store'});if(!r.ok)throw new Error(`${p} indisponível`);return r.json()};
  const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
  let PAGE=1; const PER=50;

  function historyText(h){if(!h)return'—';return [2022,2024].map(y=>{const z=h[String(y)];return z?`${y}: ${Number(z.votos||0).toLocaleString('pt-BR')} votos • ${safe(z.cargo)} (${safe(z.partido)})`:null}).filter(Boolean).join('<br>')||'—'}
  function topMunicipios(h){const p=[];for(const y of [2022,2024]){const z=h?.[String(y)];if(z?.topMunicipios?.length)p.push(`<strong>${y}</strong>: `+z.topMunicipios.slice(0,3).map(m=>`${safe(m.municipio)} (${Number(m.votos).toLocaleString('pt-BR')})`).join(', '))}return p.join('<br>')||'—'}

  async function render(){
    document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.view==='oficial'));
    view.innerHTML='<div class="card"><h2>Banco de candidatos</h2><p class="muted">Carregando dados oficiais do TSE...</p></div>';
    try{
      const [o,h]=await Promise.all([fetchJson('official-data.json'),fetchJson('election-history.json').catch(()=>({byCandidate:{}}))]);
      const monitorados=new Set(Object.values(o.candidates||{}).map(x=>String(x.sqCandidato||'')));
      const source=o.database||[], cargos=[...new Set(source.map(x=>x.cargo))].sort((a,b)=>a.localeCompare(b,'pt-BR')), partidos=[...new Set(source.map(x=>x.partido).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'pt-BR')), situacoes=[...new Set(source.map(x=>x.situacao).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'pt-BR'));
      view.innerHTML=`<div class="section-title"><div><h2>Banco de candidatos</h2><p>Cadastro oficial de 2026, patrimônio declarado e histórico eleitoral de 2022/2024.</p></div><span class="model-pill">${Number(o.databaseCount||source.length).toLocaleString('pt-BR')} candidatos</span></div>
      <div class="official-summary"><div class="kpi"><div class="label">Última consulta TSE</div><div class="value small-value">${safe(fmtDate(o.checkedAt))}</div><div class="hint">Candidaturas e bens</div></div><div class="kpi"><div class="label">Banco atual</div><div class="value">${Number(o.databaseCount||source.length).toLocaleString('pt-BR')}</div><div class="hint">MG + Presidência</div></div><div class="kpi"><div class="label">Histórico</div><div class="value small-value">${h.checkedAt?safe(fmtDate(h.checkedAt)):'Aguardando'}</div><div class="hint">Eleições 2022 e 2024</div></div></div>
      <div class="cargo-counts">${Object.entries(o.countsByCargo||{}).map(([k,v])=>`<span><strong>${Number(v).toLocaleString('pt-BR')}</strong> ${safe(k)}</span>`).join('')}</div>
      <div class="toolbar official-toolbar"><input id="oq" placeholder="Buscar nome, número, partido, ocupação…"><select id="ocargo"><option value="">Todos os cargos</option>${cargos.map(x=>`<option>${safe(x)}</option>`).join('')}</select><select id="opartido"><option value="">Todos os partidos</option>${partidos.map(x=>`<option>${safe(x)}</option>`).join('')}</select><select id="osit"><option value="">Todas as situações</option>${situacoes.map(x=>`<option>${safe(x)}</option>`).join('')}</select><select id="oord"><option value="nome">Ordenar por nome</option><option value="pat">Maior patrimônio</option><option value="v2022">Mais votos em 2022</option><option value="v2024">Mais votos em 2024</option></select><label class="check"><input id="omon" type="checkbox"> Só monitorados</label></div><div id="officialResult"></div>`;
      const hv=x=>h.byCandidate?.[x.sqCandidato]||{};
      const draw=()=>{let a=[...source];const q=norm(document.querySelector('#oq').value),cargo=document.querySelector('#ocargo').value,part=document.querySelector('#opartido').value,sit=document.querySelector('#osit').value,only=document.querySelector('#omon').checked,ord=document.querySelector('#oord').value;
        a=a.filter(x=>(!q||norm(`${x.nomeUrna} ${x.nomeCompleto} ${x.numero} ${x.partido} ${x.ocupacao}`).includes(q))&&(!cargo||x.cargo===cargo)&&(!part||x.partido===part)&&(!sit||x.situacao===sit)&&(!only||monitorados.has(String(x.sqCandidato))));
        if(ord==='pat')a.sort((x,y)=>(y.patrimonio||0)-(x.patrimonio||0));else if(ord==='v2022')a.sort((x,y)=>(hv(y)['2022']?.votos||0)-(hv(x)['2022']?.votos||0));else if(ord==='v2024')a.sort((x,y)=>(hv(y)['2024']?.votos||0)-(hv(x)['2024']?.votos||0));else a.sort((x,y)=>(x.nomeUrna||x.nomeCompleto).localeCompare(y.nomeUrna||y.nomeCompleto,'pt-BR'));
        const pages=Math.max(1,Math.ceil(a.length/PER));PAGE=Math.min(PAGE,pages);const sub=a.slice((PAGE-1)*PER,PAGE*PER);
        document.querySelector('#officialResult').innerHTML=`<div class="result-meta"><strong>${a.length.toLocaleString('pt-BR')}</strong> candidatos encontrados</div><div class="table-wrap"><table><thead><tr><th>Candidato</th><th>Cargo</th><th>Partido</th><th>Situação</th><th>Patrimônio 2026</th><th>Histórico eleitoral</th><th>Principais municípios</th></tr></thead><tbody>${sub.map(x=>{const hx=hv(x);return `<tr><td><strong>${safe(x.nomeUrna||x.nomeCompleto)}</strong><br><small>${safe(x.nomeCompleto)}</small><br><span class="number-chip">${safe(x.numero)}</span>${monitorados.has(String(x.sqCandidato))?'<span class="monitored-chip">Monitorado</span>':''}</td><td>${safe(x.cargo)}</td><td>${safe(x.partido)}${x.federacao?`<br><small>${safe(x.federacao)}</small>`:''}</td><td><span class="tse-status ${statusClass(x.situacao)}">${safe(x.situacao||'Não informado')}</span></td><td><strong>${money(x.patrimonio)}</strong><br><small>${Number(x.qtdBens||0)} bem(ns)</small></td><td>${historyText(hx)}</td><td class="status">${topMunicipios(hx)}</td></tr>`}).join('')}</tbody></table></div><div class="pager"><button id="prev" ${PAGE<=1?'disabled':''}>← Anterior</button><span>Página ${PAGE} de ${pages}</span><button id="next" ${PAGE>=pages?'disabled':''}>Próxima →</button></div><div class="note"><strong>Critério histórico:</strong> votos do 1º turno agregados dos arquivos oficiais de votação nominal por município e zona do TSE. O cruzamento usa nome completo e data de nascimento quando disponíveis.</div>`;
        document.querySelector('#prev')?.addEventListener('click',()=>{PAGE--;draw()});document.querySelector('#next')?.addEventListener('click',()=>{PAGE++;draw()});};
      ['oq','ocargo','opartido','osit','oord','omon'].forEach(id=>document.querySelector('#'+id).addEventListener('input',()=>{PAGE=1;draw()}));draw();
    }catch(err){view.innerHTML=`<div class="section-title"><div><h2>Banco de candidatos</h2><p>Camada automática de dados oficiais.</p></div></div><div class="note"><strong>Sincronização pendente.</strong> ${safe(err.message)}</div>`}
    window.scrollTo({top:0,behavior:'smooth'});
  }
  document.addEventListener('click',e=>{const btn=e.target.closest('.tab[data-view="oficial"]');if(!btn)return;e.preventDefault();e.stopImmediatePropagation();render()},true);
})();
